export const CITIES = [
	{ label: "Калининград", value: "kaliningrad" },
	{ label: "Балтийск", value: "baltiysk" },
	{ label: "Светлый", value: "svetly" },
	{ label: "Мурманск", value: "murmansk" },
	{ label: "Североморск", value: "severomorsk" },
	{ label: "Архангельск", value: "arkhangelsk" },
	{ label: "Северодвинск", value: "severodvinsk" },
	{ label: "Онега", value: "onega" },
	{ label: "Новороссийск", value: "novorossiysk" },
	{ label: "Сочи", value: "sochi" },
	{ label: "Туапсе", value: "tuapse" },
	{ label: "Геленджик", value: "gelendzhik" },
	{ label: "Анапа", value: "anapa" },
	{ label: "Ейск", value: "yeisk" },
	{ label: "Таганрог", value: "taganrog" },
	{ label: "Приморско-Ахтарск", value: "primorsko-akhtarsk" },
	{ label: "Астрахань", value: "astrakhan" },
	{ label: "Лагань", value: "lagan" },
	{ label: "Махачкала", value: "makhachkala" },
	{ label: "Каспийск", value: "kaspiysk" },
	{ label: "Дербент", value: "derbent" },
	{ label: "Магадан", value: "magadan" },
	{ label: "Оха", value: "okha" },
	{ label: "Поронайск", value: "poronaysk" },
	{ label: "Владивосток", value: "vladivostok" },
	{ label: "Находка", value: "nakhodka" },
	{ label: "Большой Камень", value: "bolshoy-kamen" },
	{ label: "Советская Гавань", value: "sovetskaya-gavan" },
	{ label: "Ванино", value: "vanino" },
	{ label: "Анадырь", value: "anadyr" },
];
